# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  coders24four.com:
    site_hosts:
      - canonical: coders24.local
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: webdev24by7@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
